# Generated by Django 2.2.24 on 2021-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0038_project_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='文章阅读量'),
        ),
    ]
